name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./helloWorld
        with:
          MY_NAME: "Zeus"
